name: fitted_scale
description: "A widget that scales its child prior to layout, the final rendering box consumes only as much space as required by the scaled child."
version: 1.0.3
homepage: https://github.com/wahahachan/fitted_scale
repository: https://github.com/wahahachan/fitted_scale

screenshots:
  - description: "Rendering box shrinks accordingly when scaling down."
    path: example/img/scale1.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: